### PR TITLE
ethtool: add support for private flags

### PR DESCRIPTION
**Pull request by lorenz**
This adds support for geting and setting private flags which are driver-specific (and sometimes even model-specific) controls not part of any generic network settings API.

They are used to toggle low-level features in various NICs.

There are currently no tests in this, considering the driver-specific nature of this I am not sure how to best add some. This has been experimentally tested on Linux 6.1 LTS and seems to work fine.

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
Seems reasonable, are there any example known flags that are common that we could document here?

**Comment by mdlayher** [comment]
`client_linux_test.go` has some examples of tests that pack and unpack datastructures which may be good to have for these.

We also want to make sure this builds on non-Linux, see the mac build failures. Otherwise seems good so far.

**Comment by lorenz** [comment]
@mdlayher Added some tests based on ethtool reference values and fixed the MacOS build.

**Review by mdlayher — APPROVED** [review]
LGTM, well done.

**Comment by mdlayher** [comment]
Ah, looks like an easy fix:
```
Error: ./client.go:322:26: too many arguments in call to c.c.PrivateFlags
	have (Interface)
	want ()
```

**Comment by lorenz** [comment]
@mdlayher Fixed, now actually cross-build-tested and passing.

**Pull request merged**
